#!/bin/sh
exec 2>&1
exec envdir ./env \
    sh -c '
      export LANG=en_US.UTF-8
      td_agent=/usr/lib/fluent/ruby/bin/ruby
      if [ -f "/usr/lib64/fluent/ruby/bin/ruby" ]; then
        td_agent=/usr/lib64/fluent/ruby/bin/ruby
      fi
      TD_AGENT_ARGS="/usr/sbin/td-agent --log /var/log/td-agent/td-agent-$PORT.log"
      INLINE_CONFIG="-i <source>\n type forward \n port $PORT \n </source> "
      exec \
        setuidgid td-agent \
        $td_agent $TD_AGENT_ARGS "$INLINE_CONFIG"
    '
